version: '3'

services:
  jarvis:
    build:
      context: ./jarvis
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    volumes:
      - ./jarvis:/app
    environment:
      - NODE_ENV=production
